---
name: Publish

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install
        run: npm ci

      - name: Lint commit messages
        run: npx commitlint --from origin/master --to HEAD

      - name: Semantic release
        run: npx semantic-release
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
